odevpl/wdp-2310

src/components/features/ProductSearch/ProductSearch.module.scss
Problem:
źle ostylowany Select w wyszukiwaniu produktu w menu
Rozwiązanie:
zmiana rozmiaru czcionki, usunięcie outline, dodanie hoveru
=> WDP231003-7

src/styles/settings.scss
Problem:
Bałagan w definicjach zmiennych kolorów
Rozwiązanie:
Nadanie kolorom własnych zmiennych, użycie tych zmiennych do określenia kolorów poszczególnych elementów na stronie
=> WDP231003-8

src/components/common/FeatureBox/FeatureBox.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.js
Dodanie trybów responsive dla kart korzyści ("Free shipping", etc.).
W trybach tablet i mobile elementy po 2 w 2 rzędach. Zachowanie takiej samej wysokości dla wszystkich elementów.
=> WDP231003-16

src/components/features/NewFurniture/NewFurniture.js
Dodane tryby responsive dla sekcji "New furniture".
=> WDP231003-17

src/components/layout/Footer/Footer.js
Dodanie trybów responsive dla stopki.
=> WDP231003-18

src/components/common/ProductBox/ProductBox.js, src/components/features/ProductSearch/ProductSearch.js, src/components/features/ProductSearch/ProductSearch.module.scss, src/styles/settings.scss
Categories dropdown in Search, fix settings of color variables"- uzupełnione brakujące zmienne kolorów, wprowadzona nowa zmienna koloru, zapisana w oczekiwanej formie w settings.scss
=> Wdp231003 10  

src/components/common/Button/Button.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/styles/settings.scss
Zostały stworzone 2 propozycje placeholderów w pliku settings. Jeden powiększa button, a drugi lekko go przesuwa, w momencie najechania kursorem. Zostały również stworzone 2 zmienne dla modyfikacji prędkości transformacji.
=> task WDP231003-9

src/components/features/NewFurniture/NewFurniture.js, src/components/features/Swipeable/Swipeable.js
Został dodany komponent Swipeable który wrapuje galerię zdjęć w wyświetlaną w new Furniture
=> WDP231003-13

src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss, src/redux/initialState.js, yarn.lock
Dodałem paru produktom starą cene w initialstate, oraz uwarunkowałem jej wyswietlanie w productbox
=> WDP231003-6

src/components/common/FeatureBox/FeatureBox.module.scss, src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/views/Popup/Popup.js, src/components/views/Popup/Popup.module.scss
Dodałem nowy komponent "Popup" w katalogu  Views, jest dzieckiem ProductBox, skąd pobiera propsy.
=> WDP231003-37

src/components/features/NewFurniture/NewFurniture.js, src/components/views/Homepage/Homepage.js, src/components/views/ProductPage/ProductPage.js
Dodaem do komponentu NewFurniture zmienną productsPerPage, która steruje ilością wyświetlanych produktów w NewFurnitire. Podczas renderowania komponentu NewFurniture w HomePage przekazywana jest liczba 8 jako productsPerPage, natomiast podczas renderowania komponentu ProductPage  jako productsPerPage przekazywana jest liczba 4 co zapewnia, że w sekcji NewFurnitue na podstronie ProductPage wyświetlane są 4 produkty. Na podstronę produktu można wejść ze ścieżki  '/product/:productId'.
=> WDP231003-45

src/App.js, src/components/features/RegisterForm/RegisterForm.js, src/components/features/RegisterForm/RegisterForm.module.scss, src/components/layout/TopBar/TopBar.js, src/components/views/RegisterPage/RegisterPage.js, src/components/views/RegisterPage/RegisterPage.module.scss
Dodałem strone komponent nowej strony registerPage, oraz osobny komponent z formularzem
=> WDP231003-46

src/App.js, src/components/common/ProductBox/ProductBox.js, src/components/layout/MenuBar/MenuBar.js, src/components/views/Blog/Blog.js, src/components/views/Blog/Blog.module.scss
Dodane linki do menu głównego, utworzona pusta podstrona blog oraz dodane linki do produktów (zdjęcie i nazwa)
=> WDP231003-36

src/components/features/NewFurniture/NewFurniture.js, src/components/features/Sales/Sales.js
Przepisałem komponent NewFurniture jako funkcję. Dodatkowo pozwoliłem sobie usunąć propTypes z komponentu Sales ponieważ doszedłem do wniosku że były tam niepotrzebnie użyte i chociaż nie wpływały na działanie strony pojawiały się niepotrzebne błędy w konsoli. Komponent Sales robiłem w którymś z poprzednich tasków, więc mam nadzieję że nie jest to problem że trochę go zmodyfikowałem.
=> WDP231003-35

src/components/common/Button/Button.module.scss, src/components/layout/FeaturedCard/FeaturedCard.js, src/components/layout/FeaturedCard/FeaturedCard.module.scss, src/components/layout/FeaturedProduct/FeaturedProduct.js, src/components/layout/FeaturedProduct/FeaturedProduct.module.scss, src/components/layout/SectionFeatured/SectionFeatured.js, src/components/layout/SectionFeatured/SectionFeatured.module.scss, src/redux/productsRedux.js
Problem:
W tym zadaniu należy dodać funkcjonalność do dwóch sliderów w sekcji "Promowane":
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-featured.png 
Wymagania
Slidery mają działać niezależnie od siebie, tzn. przesuwanie jednego nie powinno wpływać na drugi.
Slider po lewej powinien mieć autoplay (3 sekundy). Niezależnie od tego powinna działać nawigacja (kropki nad sliderem), by dało się przełączać slajdy ręcznie (kliknięcie ma wstrzymywać autoplay na 10 sekund). Kropka przy aktywnym slajdzie powinna być pomarańczowa.
W sliderze po prawej nie ma być autoplay'a, nawigacja w nim powinna być możliwa tylko przy pomocy strzałek.
Oba slidery mają mieć animację fade, tak samo jak sekcja New Furnitiure (do niej była dodana animacja w innym zadaniu)
Rozwiązanie:
Dodałam …
=> WDP231003-23

src/components/features/NewFurniture/NewFurniture.js, src/components/layout/Brands/Brands.js
Dodałem funkcjonalność do komponentu Brands, która w zależności od wartości screenMode zapisanej w initialState zmienia ilość wyświetlanych zdjęć w sekcji Brands. Tak samo powinna zmieniać się ilość zdjęć o którą przesuwa się slider przy kliknięciu w button. Tak więc dla wartości desktop powinno wyświetlać się 6 zdjęć z markami i o tyle samo zdjęć powinien przesuwać button przy kliknięciu. Dla wartości tablet ustawione jest 3 zdjęcia na stronę dla mobile 2. Z tego co zauważyłem screenMode zapisywany jest w aplikacji  raz przy ładowaniu strony, więc żeby zobaczyć wpływ zmiany tej wartości na komponent na którym pracowałem należy zmienić okno w przeglądarce i odświeżyć stronę.
=> WDP231003-31

src/components/features/Chatbot/Chatbot.js, src/components/features/Chatbot/Chatbot.module.scss
Problem:
Przygotuj chat bot na kilka pytań (możesz improwizować).
Ważne jest, że gdy w wiadomości pojawią się słowa kluczowe, ten odpowie konkretnym zdaniem:
_**Słowo kluczowe - Odpowiedź**_
- cena dostawy - Cena dostawy wynosi 50zł
- opcje dostawy - Korzystamy z kuriera firmy DPD
- ile produktów - Jeden kurier może dostarczyć do 10 produktów.
- czas oczekiwania - Czas oczekiwania na produkty wynosi 20 dni
- instrukcje montażu - Tak, każdy mebel zawiera instrukcję montażu
- gwarancja - Tak, meble są objęte 2 letnią gwarancją
- zwrot - Meble można zwrócić do 14 dni na koszt sklepu
- metody płatności - Za meble można zapłacić przelewem i przy odbiorze
_Jeśli słowo klucz nie wystąpi, odpowiedź brzmi:_
-W takim przypadku proponuję kontakt z naszym pracownikiem. Czy mogę pomóc w czymś jeszcze? …
=> Wdp231003 41

src/components/features/Chatbot/Chatbot.js, src/components/features/Chatbot/Chatbot.module.scss
Poprawka by wiadomość użytkownika również pokazywała się na czacie!
Dodatkowo:
- dodałem lightgreen (kolor) na background odp użytkownika by było ładnie i informowało że to Twoja wiadomość (nie dodawałem $ ale mogę by sobie klient mógł zmienić w przyszłości)
=> WDP231003-41 | Fix ChatBot class and module (add user ask to chat)

src/components/layout/Feedback/Feedback.js, src/components/layout/Feedback/Feedback.module.scss, src/redux/initialState.js
Dodałem funkcjonalność przesuwania wpisów w sekcji Feedback za pomoc Swipeable lub klikania na kropki. Dodałem do magazynu 2 dodatkowe feedbacki żeby można było przetestować funkcję przełączania wpisów.
=> WDP231003-34

src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/CompanyClaim/CompanyClaim.module.scss
ticket stworzony przeze mnie
Problem:
W sekcji CompanyClaim ikona koszyka jest w złym miejscu - powinna być dosunięta do prawej strony zgodnie z designem.
Oprócz tego logo sklepu po kliknięciu powinno przenosić do strony głównej.
Rozwiązanie:
Dodałam href na taki prowadzący do strony głównej. Ustawiłam ikonę koszyka przy pomocy flexa
=> WDP231003-63

src/components/common/Button/Button.module.scss, src/components/features/ProductDetails/ProductDetails.js, src/components/features/ProductDetails/ProductDetails.module.scss, src/components/views/ProductPage/ProductPage.js, src/components/views/ProductPage/ProductPage.module.scss, src/styles/settings.scss
Na podstawie wizualizacji - Stworzenie na podstronie produktu sekcji, która pokazuje dane konkretnego produktu.
Zadanie nie dotyczy funkcjonalności oraz RWD.
Wizualizacja: 
https://kodillameet.pl/pg/przeglad_produktu.png
=> Wdp231003 43

src/components/common/ProductBox/ProductBox.js, src/components/features/Cart/Cart.js, src/components/features/Cart/Cart.module.scss, src/components/layout/CompanyClaim/CompanyClaim.js, src/redux/cartRedux.js
Aktualnie na stronie koszyka pojawiają się tylko statyczne produkty.  Twoim zadaniem jest zaprezentowanie produktów, które faktycznie zostały dodane do koszyka po kliknięciu przycisku AddToCart. Ticket dotyczy nazwy produktu, zdjęcia oraz ceny pojedynczej sztuki.
AC:
1. Po kliknięciu w przycisk AddToCart dany produkt pojawi się w podstronie koszyka.
2. Wyświetlona ma zostać jego nazwa, zdjęcie i cena. (funkcjonalność ilości zostanie dodana w innym tickecie)
Produkty można kasować z listy po kliknięciu krzyżyka przy zdjęciu.
Po kliknięciu przycisku PROCEED TO CHECKOUT wszystkie produkty z koszyka znikają z listy.
TERAZ:
można dodawać produkty, usuwać pojedynczo i wszystkie naraz przy użyciu Proceed to checkout.
=> WDP231003-49

src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/Chatbot/Chatbot.module.scss, src/components/features/CompareStickyBar/CompareStickyBar.js, src/components/features/CompareStickyBar/CompareStickyBar.module.scss, src/components/layout/MainLayout/MainLayout.js, src/redux/initialState.js, src/redux/productsRedux.js
Stworzyłem nowego brancha "WDP231003-122", ponieważ jest to zadanie które przejąłem po Ani, zmergowanie tego starego brancha jest w tym momencie prawie niewykonalne, ponieważ wisi to tu już dwa tygodnie, dużo łatwiej było mi napisać to wszystko od nowa.
Dodałem nowy komponent CompareStickyBar, przesunąłem też trochę do góry okno chatbota, ponieważ nachodziły na siebie.
=> WDP231003-12

src/components/layout/FeaturedCard/FeaturedCard.module.scss, src/components/layout/FeaturedProduct/FeaturedProduct.module.scss
Zrobiłem kosmetyczne zmiany w stylach featuredProduct i featuredCart.
=> WDP231003-24

src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss, src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/CompanyClaim/CompanyClaim.test.js
Problem:
Obecnie w widgecie koszyka widnieje wartość, która nie odzwierciedla prawdziwej ilości produktów w koszyku.
Twoim zadaniem jest dodanie funkcjonalności, która sprawi, że obok koszyka pojawi się faktyczna wartość.
Rozwiązanie:
- po kliknięciu ADD TO CARD - dany produkt jest dodawany do karty koszyka, wraz z klikniętą ilością
Dodatkowo:
- dodałem alert nad boxem produkty, informujący o tym że produkt został dodany do koszyka.
- zmieniłem testy w CompanyClaim, gdyż miałem z nimi problem w renderowaniu
=> WDP231003-59

src/components/features/Chatbot/Chatbot.module.scss, src/components/layout/BlogSection/BlogSection.module.scss, src/components/layout/Brands/Brands.module.scss
Problem:
Zadaniem jest stworzenie wersji mobilnych sekcji "Brands". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
W sliderze ma być tyle elementów, ile zmieści się w całości na danej szerokości ekranu.
Ma działać przesuwanie slajdów za pomocą komponentu Swipeable (jest na niego osobne zadanie – jeśli nie jest gotowe to trzeba przygotować funkcje, które będą wykonywane przy swipe w lewo i w prawo).
Rozwiązanie:
- dodanie wersji mobilnych dla komponentu Brands,
Dodatkowo:
- gdy dla rozdzielczości mniejszej od 992, sekcja Blogu wjeżdżała swym opisem na Brands - pozwoliłem sobie zmniejszyć czcionkę w sekcji Blog aby nie najeżdżała na Brands
=> WDP231003-32

src/App.js, src/components/features/ProductSearch/ProductSearch.js, src/components/layout/MenuBar/MenuBar.test.js, src/components/views/SearchPage/SearchPage.js, src/components/views/SearchPage/SearchPage.module.scss
Dodałem nową stronę SerchPage, musiałem zmienić test MenuBar, bo były jakieś problemy w renderowaniu.
=> WDP231003-56

src/components/features/Chatbot/Chatbot.js, src/components/features/Chatbot/Chatbot.module.scss, src/components/features/CompareStickyBar/CompareStickyBar.js
Ticket zrobiony przeze mnie
Problem:
Teraz sticky bar na dole strony wyświetla się cały czas, co wygląda niezbyt dobrze i przeszkadza w przeglądaniu strony. Trzeba to poprawić tak, żeby wyświetlał się on dopiero po dodaniu jakiegoś produktu do porównania
Teraz: stickybar pojawia się tylko kiedy zostanie dodany do niego produkt
=> WDP231003-64

src/components/common/Button/Button.module.scss, src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss
Ticket zrobiony przeze mnie
Dodanie jednolitego stylowania dla buttonów ULUBIONE i PORÓWNANIE, co by było ładnie i spójnie
=> WDP231003-65
